### ISSUE TITLE
[Bug]: response failed

### ISSUE THREAD

**Issue by AlaaYasser0210** [remotely-save/remotely-save#107]
### What happened?

At last step of syncing. This message appears (response failed with a 409 code)

### What OS are you using?

iOS (iPhone, iPad), Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

Last version

### Version of Obsidian

Last version

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Do you have any emojis in file names? Or any special characters in file names?

**Comment by AlaaYasser0210** [comment]
> 

No, I don't. No emojis or special characters

**Comment by fyears** [comment]
Is it a folder or a file? Can you reproduce the error in a new test vault with the same file / folder name?

**Comment by AlaaYasser0210** [comment]
> Is it a folder or a file? Can you reproduce the error in a new test vault with the same file / folder name?

![IMG_20220506_233109](https://user-images.githubusercontent.com/100446158/167219136-aa0aefa1-74c6-40d5-b83e-34744a22ad8f.jpg)
This message always appears.

**Comment by fyears** [comment]
Can you reproduce the error on Android or computers?

If so, would you please follow the guides here and see if there is any more hints about what's going on inside the console?

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

**Comment by AlaaYasser0210** [comment]
> Can you reproduce the error on Android or computers?
> 
> If so, would you please follow the guides here and see if there is any more hints about what's going on inside the console?
> 
> https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

Thank you for replying.
It happens on Android too.
I don't have pc to follow the instructions in the link you provided.
I am syncing between ipad and android phone.
Is there a possibility to fix this without pc?

**Comment by AlaaYasser0210** [comment]
I tried onedrive instead of Dropbox. The first on android and ipad to connect to onedrive was successful. But When I clicked to sync now to fetch data of each to the other it fails 
![IMG_20220507_140934](https://user-images.githubusercontent.com/100446158/167253929-863cb748-4e59-473c-ba23-d904797d392b.jpg)

**Comment by fyears** [comment]
I have no clue yet.

You can try to "hard reset" the plugin.

1. **Back up your vault elsewhere firstly**
2. Open remotely save settings, scroll down to the bottom, click the "reset" button in the section "Reset Local Internal Cache/Database"
3. Disable and uninstall the plugin
4. On your Dropbox web page, go to `/Apps/remotely-save/<your vault name>`, delete that `<your vault name>` folder. So that next time the plugin can automatically create the folder and upload every thing again.
5. Restart your Obsidian app, and re install the remotely-save plugin, and configure Dropbox account on the plugin again.
6. Try to sync again.

**Comment by fyears** [comment]
closed because no further reply for a while
