### ISSUE TITLE
[Bug]: Creation/modified date on Webdav

### ISSUE THREAD

**Issue by aubreyz** [remotely-save/remotely-save#120]
### What happened?

This may be a misunderstanding my end as to what is expected. The file creation/modification dates/times on the Webdav are the times at which the transfer took place, not the properties of the file. 

This does not seem to be an issue with my Webdav, as other software I use to transfer to Webdav, maintains the correct dates. 

How then will synchronisation work, because it will not be a matter of which system (remote from the Webdav) has the newest file, but only which did the most recent manual synch of a file which had been changed at any time before that synch. 

It also makes it impossible to verify that the Webdav also contains a correct synch without comparing file contents. I'm not encrypting so it is just a native file. 

The _remotely-save-metadata-on-remote.json is fairly small, so is not going to contain the actual file dates. 

So I am confused as to how this will work.  I think there needs to be better documentation anyway as to what is going on under the hood and how decisions are made.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.2.5

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi thanks for asking. It seems that you want to know how the sync algorithm works.

> The file creation/modification dates/times on the Webdav are the times at which the transfer took place

Whatever timestamps the server returns.

> because it will not be a matter of which system (remote from the Webdav) has the newest file, but only which did the most recent manual synch of a file which had been changed at any time before that synch.

Assuming you always use Obsidian by youself only, and at any moment you only work on one device. Also assuming all the clients and servers have correct and accurate timestmaps. Here are some examples, you can compare them and “feel” the idea behind the plugin:

* You edit the file A on device 1, then sync on deivce 1. Then on device 2, you **do not edit** the file A, and start syncing. In this situation, the server timestamp of file A is always larger than the client timestamp of file A on device 2 (**no matter whether the server time is the “server creation time” or “file property time”**). Then the sync process would download the server file and overwrite the device 2 file.
* You edit the file A on device 1, then sync on deivce 1. Then on device 2, you **do edit** the file A, and start syncing after editing. In this situation, the server timestamp of file A is always **smaller** than the client timestamp of file A on device 2 (**no matter whether the server time is the “server creation time” or “file property time”**). Then the sync process would upload the devoce 2 file and overwrite the server file. And since the plugin do not have the “merging contents” mechanism, you do lose your previous work on device 1, of which you should be aware before editing the file on device 2.

> The _remotely-save-metadata-on-remote.json is fairly small, so is not going to contain the actual file dates.

Currently it only contains the deleted files info, so that deletion operations can be synced.

> I think there needs to be better documentation anyway as to what is going on under the hood and how decisions are made.

https://github.com/remotely-save/remotely-save/blob/master/docs/sync_algorithm_v2.md

**Comment by aubreyz** [comment]
As I suspected this sounds like a serious bug to me (the failure of the transfer mechanism to give the file in the brokering repository the correct file date/time). The scenarios you describe are not the problematical ones. 

a) Everyone accepts that where files differ, it is possible that a newer (changed) version might overwrite an older (changed) version - losing some data in the process. But that is not what might happen here. The correct scenario is

b)
- User maintains vault on Laptop A and B
- On 1st January many files are minimally altered on Laptop A. For whatever reason Laptop A does not synchronise at that time (it was not done manually, or there was no internet access, or it is set to do every 10 minutes and machine obsidian is closed at 9 minutes)
- In 1st February user does extensive edits on Laptop B offline to the files already altered a month before on A and there is no synchronisation. 
- On 2nd February user opens Laptop A, does a minor edit to one unrelated file, and autosynch takes place. All the files altered on 1st January now have the date 2nd February on the server but with file contents of 1st January from Laptop A. 
- On 3rd February user opens Laptop B and all his NEWER edits are overwritten by files that are two months old (but incorrectly dated causing the flow to go in the wrong direction) losing all information for a month. 

Other synch systems do not work that way. As far as I know, Google Drive, Obsidian Synch, Dropbox, Rclone, foldersync on android .... all maintain the correct timestamp -- so the worst that can happen is that when there is a conflict the newer contents will overwrite older contents. This is NOT what will happen here. 

I think this bug needs to be re-opened, and all efforts need to be made to warn users that this will happen, and that file dates are not maintained. 

By way of an analogy the reason you are keeping a json file showing deletions, is that the system cannot know whether a missing file on one side represents a deletion or a new addition. In exactly the same way, if filestamps are not kept there is no way to know which is the newer file when there is a conflict, because the later dated file (on the broker) could easily be the older file - or even very old file.

**Comment by fyears** [comment]
> the failure of the transfer mechanism to give the file in the brokering repository the correct file date/time

This is **another aspect** of the reliability of the plugin, not necessarily related to the syncing algorithm. Firstly, admittedly that "avoid broken files" is not specially handled by me, and I just bundle a js WebDAV library for uploading and downloading. Secondly, my WebDAV server would not recognize or show up the file until it is uploaded completely. Thirdly it's indeed possible to add some checking on the plugin side, like comparing the md5 values of the uploaded file and the local file, by requiring extra computational resources (and battery), which I may consider in the future releases.

> Other synch systems do not work that way. As far as I know, Google Drive, Obsidian Synch, Dropbox, Rclone, foldersync on android .... all maintain the correct timestamp.

I don't think so.

Especially for WebDAV, extra efforts are needed to keep the "file property last modified time". Because Webdav is a standardized protocol, we want to find a "universal solution" for **any** WebDAV provider.

1. Official clients of Google Drive, Obsidian Sync, and Dropbox, may (or may not, I don't know), have saved the "file property last modified time". It's quite technically possible because the providers implement both the server sides and client sides, so they can add the support as soon as they want.
2. But for rclone for WebDAV, see https://rclone.org/webdav/#provider-notes . Rclone **only** supports adding **non-standard** `X-OC-Mtime` for Owncloud and NextCloud to keep the modified time.
3. Also, for foldersync for WebDAV, see https://www.tacit.dk/foldersync/faq/#when-are-modification-timestamps-for-files-updated . Foldersync **does not** support "setting modified timestamp of uploaded files" for WebDAV.

Coming back to discuss the syncing algorithm of remotely-save, it's indeed technically possible to save the "file property last modified time" in `_remotely-save-metadata-on-remote.json`. This may be added in future releases.

> By way of an analogy the reason you are keeping a json file showing deletions ...

There are subtle differences. Almost all the cloud providers do not provide the information of deleted files easily. But almost all the cloud providers provide some sort of last modified time of the existing files, although not perfectly identical to "file property last modified time".

**Comment by fyears** [comment]
Tl'dr, it's indeed technically possible to save the "file property last modified time" in `_remotely-save-metadata-on-remote.json`. This may be added in future releases.

**Comment by fyears** [comment]
will be considered in later version. close this issue now
