### ISSUE TITLE
[Bug]: "Do not know which level for /FolderName/"

### ISSUE THREAD

**Issue by vaqxai** [remotely-save/remotely-save#132]
### What happened?

While trying to sync, I'm getting an error "Do not know which level for /FolderName/" (The name contains Polish characters: "ł,ą").
I'm syncing via webdav to a OwnCloud instance.

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Could you please provide an example folder name containing Polish symbols, so that I can test the logic dealing with folder levels? (I do not know Polish)

And maybe you can also try directly uploading the Polish-symbols-file-name file onto Owncloud, using Owncloud's web page, not remotey-save, to see whether the file name was changed insided Owncloud.

**Comment by vaqxai** [comment]
Zażółć Gęślą Jaźń

**Comment by Steven-AA** [comment]
![image](https://user-images.githubusercontent.com/22387129/224868200-4d550822-67ef-4f5a-b9ae-e2a8d933392b.png)

same problem here, macos, jianguoyun webdav.

**Comment by fyears** [comment]
dup of #388

but not closing this yet because users are speaking different languages...

**Comment by fyears** [comment]
new version (0.4.12) changes the sync algorithm and hopefully fixes this bug
