### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by uroybd** [remotely-save/remotely-save#280]
### What happened?

I used this plugin with no issues. However, there are no interaction from maintainer's part for quite a long time.

Is this project abandoned completely?

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by varuncupid** [comment]
pls send setup config. when i try to setup between window and android the folder does' not sync properly

**Comment by bamsammich** [comment]
+1 Have the same concern. Plugin works as expected but there hasn't been a commit in almost a year.

**Comment by eric-pierce** [comment]
It does seem like this project is abandoned given no commits in the past year. As best I can tell these are two potential (but different) alternatives:

1. Live syncing across clients: https://github.com/vrtmrz/obsidian-livesync
2. Use git as the notes backend: https://github.com/denolehov/obsidian-git

I'm hoping that if the developers are done maintaining this someone will either take over or fork this project.

**Comment by fyears** [comment]
Hi all. I am the plugin user.

Firstly thank you all for your support!!!

Admittedly I was too busy (well I DO have a job so that I could earn money and food...) and too lazy to update the plugin in the past few years.. 

Furthermore, I personally kept using my plugin to sync my notes over s3, so far so good. I did not directly encounter a reproducible bug by myself. Thus I do not have a very good reason to update the functions of the plugin.

But anyways, since I am likely to keep using the plugin unless anyone in community provides a better one. I will keep maintaining this plugin in the future!

BTW, livesync and obsidian-git doesn't meet my needs because the first one needs a db server and the second one do not support mobile. So I think they and remotely-save share the different "market" in community.

**Comment by berot3** [comment]
@fyears first, thank you so much. Just a thought: how about "promoting" this plugin a bit more. I'm sure you could give this repo some more time and solve the issues of the users if some more donations would come in. Maybe setting some targets or so - mkdocs-material comes to my mind. He is making a good job in turning his project into actual money. But yes, no idea what other obsidian plugins are getting for donations. With the unique features of your plugin I'm sure would keep coming if the donators would see that their donations are making a difference. 

Wish you all the best!
