### ISSUE TITLE
[Bug]: Unexpected and unknown exception causing Obsidian crashed

### ISSUE THREAD

**Issue by PassionPenguin** [remotely-save/remotely-save#286]
### What happened?

When using remotely-save + onedrive lightly, everything goes perfectly. once there's a bunch of files in the vault (even though they are all synced by OneDrive Desktop app and won't need remotely-save to update, it still crashed as soon as the plugin is loaded.

When crashed, the obsidian app itself will lose all its UI, the debug console will lose its connection to the window.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

latest/0.3.25

### Version of Obsidian

1.1.9/installer 0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi the plugin relies on the [Obsidian api to return the files list](https://github.com/remotely-save/remotely-save/blob/b238988012f63f851c56496263cf469237e78a29/src/main.ts#L264C36-L264C53). And the remote http api to return the remote files list. So technically the plugin itself would not scan the whole disk to load the data for the meta data.

May be you have some large files (so that the plugin decide to upload them and crash??) Maybe trying to set the Skip Large Files will be helpful if you are still using this plugin.
