### ISSUE TITLE
[Feature Request]: Add a feature to sync notes when closing the app.

### ISSUE THREAD

**Issue by usman-ghani-khan** [remotely-save/remotely-save#291]
### What feature are you suggesting?

To add functionality to sync the files when the app is closed.

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by yezhizi** [comment]
This is important to me. Sometimes I forget to sync in time after work, it cause me to lose some data when I start syncing on another device

**Comment by fyears** [comment]
Sorry. That’s technically impossible: because the plugin runs inside the js environment provided by obsidian, so once the obsidian is closed, everything of js code will not able to run. There is no way to workaround it unless obsidian has some sort of background api.

But anyways your issue could be partially solved in other way: the plugin already provides auto sync every x minutes. At least users could save part of the work by enabling this feature.
