### ISSUE TITLE
[Feature Request]: Allow custom Dropbox folder path

### ISSUE THREAD

**Issue by deusnovus** [remotely-save/remotely-save#293]
### What feature are you suggesting?

Duplicate of #140 , but it would be really appreciated, if Dropbox users could set a custom Dropbox folder path, instead of the default App/remotely-save folder path. Thank you!

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Actually the plugin applies for ["App folder" permission](https://www.dropbox.com/developers/reference/developer-guide). So that the plugin itself and other bad actor will at least **not able to** messy up with other files of users. I am sorry but the FR here will not be implemented in the near future unless the plugin become absolutely stable.
