### ISSUE TITLE
[Bug]: deleted file on server gets re-created by plugin

### ISSUE THREAD

**Issue by m-beau** [remotely-save/remotely-save#302]
### What happened?

I use dropbox to sync my vault. After deleting a file on my dropbox server, running the plugin sync re-creates the file on the server! The only way to currently delete a file is to delete it on the device where the plugin runs (iOS), then sync it with the server.

### What OS are you using?

iOS 16.0.2

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.2, mobile

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by LBWNB55KYYDS** [comment]
yeah, me too

**Comment by JunerLee** [comment]
the same

**Comment by BobWs** [comment]
same but then with the css snippet. I cannot remove old css snippets every time I delete the file I keeps re-creating it back in the snippet folder. When renaming the file it also keep re-creating the file. This is very annoying!

**Comment by 3cl0z10n** [comment]
I don't know if your problem is related to the way I wrongly used this plugin. 
Tested with Dropbox & OneDrive

Wrong uses : 
- share a same Vault/Folder/etc. between mobile and local

Right way : 
- configure a new Vault with RemosteSave on mobile (with same cloud service & config)
- configure a new Vault with RemosteSave on local (with same cloud service & config)

With this way, unfortunately, you'll end up with 2 folders on your cloud server : 
- App folder (sync from mobile Vault)
- A local folder (sync from local Vault)
But this is the only way I found that works properly.
Now, the file "_remotely-save-metadata-on-remote.json" is operational.

**Comment by changbowen** [comment]
I can't believe I have been using it wrong the whole time... this should be included in readme.. (maybe it already is?)

**Comment by fyears** [comment]
> Right way :

> configure a new Vault with RemosteSave on mobile (with same cloud service & config)
> configure a new Vault with RemosteSave on local (with same cloud service & config)


As long as the vault names are the same across devices, they should properly sync with each other and merge the local files together.

**Comment by fyears** [comment]
> I use dropbox to sync my vault. After deleting a file on my dropbox server, running the plugin sync re-creates the file on the server!

This is documented in <https://github.com/remotely-save/remotely-save/blob/master/docs/minimal_intrusive_design.md> Tje plugin can only track the deletion from inside Obsidian. It needs extra care to memorize what was deleted. It's a limitation but not a bug.
