### ISSUE TITLE
[Bug]: App crashes on android

### ISSUE THREAD

**Issue by hswind4** [remotely-save/remotely-save#324]
### What happened?

I'm using obsidian on my android phone, whenever I turn on this plugin for syncing, within a minute, obsidian crashes. Turn off the plugin and everything is fine I hope to solve this problem.

Mobile：Samsung s21
Appp：obsidian latest
Sync way：onedrive for personal

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Yetenol** [comment]
I am having the same issue. I already tried the following:
- Reset plugins, reinstall and reauthenticate
- Delete cloud file and sync again from my computer
- Delete cloud files and sync unencrypted from my computer

**Comment by Vytantus** [comment]
This started happening to me as well, 2 days ago. 

Mobile：Samsung Note9
Appp：obsidian 1.4.5 (104)
Sync way：WebDAV

Thing's I've tried:
- uninstalling and reinstalling app
- underscoring the most recent files to stop them syncing
- lowering/raising concurrency
- setting skip large files to different sizes
- deleting sync plans histroy in DB

It appeared to start happening after I added a few pdfs and pptx files to a few notes. 

I only use manual sync. I also have the little notifications running and it counts fine to step 7( of 8) and then hangs for 5-10s before crashing.

The plugin is running fine on my laptop (Manjaro) and PC (Xubuntu) which are using the same vault on the same WebDAV storage.

**Comment by Vytantus** [comment]
UPDATE:

Been living with this crashing issue since May (now October) as the vault seemed to be syncing changes both ways (NextCloud WEBDAV <-> Android) so treated it as a functional inconvenience. Now recently I experiemented with removing the largest files in the vault and **it started syncing without crashing.** 

Vault is a bit over 1800 files, almost all of it is in the root folder of the vault (only directories for Excalidraw and templates etc.) and there's a few hundred images and perhaps a few dozen pdfs, ptx, dox and other random small files. 

Two biggest files were PDFs. 50Mb and 40Mb. Removed them from laptop local storage. Synced on laptop. Then synced on phone and it completed with no crashes and no issues. WTF. Hope this helps someone. Or the guy that started this plugin hands over maintenance to someone who has the time!!

**Comment by fyears** [comment]
Try to set the Skip Large Files in the settings.

**Comment by mira-miracoli** [comment]
I have the same issue on GrapheneOS using the latest obsidian and remotely save versions. I really appreciate this project and of course this is all voluntary unpaid work, but I don't think this is a pure inconvenience but a major bug, because I can not sync files like books or other larger PDFs.
