### ISSUE TITLE
[Feature Request]: Selectively sync plugin and plugin settings

### ISSUE THREAD

**Issue by uroybd** [remotely-save/remotely-save#334]
### What feature are you suggesting?

A whitelist/blacklist mechanism to allow users to selectively sync plugins and settings so that some plugins (e.g. the ones don't work in phone) can be ignored.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by justrainer** [comment]
I'd like to underline this request with the following specific situation: I use a plugin to add icons to folders, and the configuration file is saved somewhere in the .obsidian folder. Problematically though, right next to this config file also lies the folder that holds the thousands of icons. Synching the entire .obsidian folder causes extreme sync speed issues due to the sheer amount of files that are checked, when I really only want to sync a couple of .json files with plugin configuration. 

It would be great if we could add either whole plugin config directories, or even better specific files from the .obsidian folder to be synced.

**Comment by fyears** [comment]
The api to access obsidian plugin folder is different from the api for normal files. It’s technically difficult to implement this feature…
