### ISSUE TITLE
[Bug]: "Failed to PutOrAdd in database because not enough space for domain"

### ISSUE THREAD

**Issue by ARMIsNOTLoaded** [remotely-save/remotely-save#352]
### What happened?

Remotely Save doesn't sync with my OneDrive Personal. Was working perfectly fine a few days ago.

Whenever it tries to sync, it returns those errors at stage 6 ("Starting to generate sync plan"):

`remotely-save-1691006533019: abort sync, triggerSource=manual, error while generating_plan`

The number 1691006533019 changes everytime I try to sync.

`Failed to PutOrAdd in database because not enough space for domain`

I don't have this problem while on my Windows 11 PC.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by LBWNB55KYYDS** [comment]
I have this problem as well

**Comment by LBWNB55KYYDS** [comment]
Is the author of this plugin still updating it?

**Comment by fyears** [comment]
Hi please click the “reset” in the bottom of the plugin settings page, and reload the plugin to see if the error goes aways. The error shows that the cache info is too large, and I guess that’s because of the history cache.

Feel free to reopen the issue if the problem still exists after the above steps.
