### ISSUE TITLE
[Bug]: Cannot load in Android

### ISSUE THREAD

**Issue by zhangpanzhan** [remotely-save/remotely-save#364]
### What happened?

0.3.25 Version cannot work in Android phones, cannot load in obsidian.

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.5

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by temeddix** [comment]
I'm experiencing this issue as well. This works well on Windows, but not in Android. `SSLHandshakeException` happens.

**Comment by fyears** [comment]
`SSLHandshakeException` issue may be similar to https://github.com/denolehov/obsidian-git/issues/552 , no way to fix.

"cannot load" the plugin is proven to be not working on older Android. Because no old Android device I could test on and no further enough info provided, the issue is closed here. Feel free to reopen a new issue if the issue can be reproduced on a newly created test vault.
