### ISSUE TITLE
[Feature Request]: Add log level of Error

### ISSUE THREAD

**Issue by hulizhen** [remotely-save/remotely-save#401]
### What feature are you suggesting?

I sync my documents a lot while editing them. The current log level (info & debug) generates excessive notifications, which can be quite annoying. It would be appreciated if you could add an Error log level (only notifying in the case of errors).

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
may i ask which notification do you mean? the console (dev tools log?)

**Comment by hulizhen** [comment]
> may i ask which notification do you mean? the console (dev tools log?)

sorry for missing your reply. i mean those logs shown on the top-right side each time it's syncing.

**Comment by fyears** [comment]
Yep so may be the messages are too many and too distracting. I would try to remove some of them in the new releases.

**Comment by jerrygreen** [comment]
Closed as completed means it's possible to hide notifications? I cannot find such a setting. Or is it completed just not yet delivered to production? Those messages are a real distraction.

Obisidian v1.5.3
Remotely Save v0.3.37

**Comment by fyears** [comment]
if you set the logging level into info, and trigger the sync manually, then the sync should only show up 2 notifications (start and end). (before that the notifications were 8 which were too many i admitted)

if you set up the auto sync, no notifications.

Really, do you want to eliminate **all** the notifications **with manual sync**? i believe some users might suspect the plugin is not working because of no obvious responses

**Comment by jerrygreen** [comment]
Just re-checked: notifications actually properly hidden, only shown on manual sync, indeed!

By some reason I thought it was shown even with log level info, but it seems I was mistaken. Sorry for bothering!
