### ISSUE TITLE
[Bug]:  Cannot read properties of null (readingctime')

### ISSUE THREAD

**Issue by huangjingyun8** [remotely-save/remotely-save#412]
### What happened?

remotely-save-1703650075480: 中断同步，同步来源=manual，出错阶段=generating plan
成功

Cannot read properties of null (readingctime')

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by huangjingyun8** [comment]
![Uploading 微信图片_20231227141913.png…]()

**Comment by fyears** [comment]
图片上传失败了，方便再看看错误是啥吗

**Comment by saurusss** [comment]
Last week remotely-save was updated and I got the same error and it won't sync.
error message is as below:
remotely-save-1704617120855:abort sync, triggerSource=manual, error while getting_local_meta
Cannot read properties of null (reading 'ctime')

**Comment by fyears** [comment]
may i ask is there any special file do you create ? or any files created outside obsidian?

**Comment by saurusss** [comment]
In version 0.3.25 of remotely-save, when I performed the sync operation in 8 steps, there was a similar message in the middle, but the sync proceeded to the end.
However, after upgrading to version 0.3.34, while performing the sync operation in 2 steps, the sync is interrupted midway through and is not reflected at all. 

I'm getting the same error when trying to share information from a Windows PC and a Macbook.
I have also forced the same information to One drive and sync from android mobile and it completes without any problem. (mobile remotely-save 0.3.34)

I'm attaching the full list because I can't find any special files you're asking for.  Hope this helps.

attachment : filelist.txt
[filelist.txt](https://github.com/remotely-save/remotely-save/files/13873373/filelist.txt)

**Comment by huangjingyun8** [comment]
我解决问题的方式很奇怪，我先更改 同步方式  用 dropbox 来同步一阵，再更换回 缤纷云的S1 ，问题解决了

**Comment by saurusss** [comment]
The file in the .obsidian folder seems to be wrong. I copied the 'md' file to a new folder, reinstalled the plugin, and the sync goes fine.
Thanks.

**Comment by Pongpun364** [comment]
I got similar problem. On my window 10 machine when i click on "sycn" button, got this message **"can not read properties of undefined ( reading 'adapter' )"**
**Plugin Version**: 0.3.35
At the same time, on my iphone, it is working just fine (**Plugin Version**: 0.3.34)

![image](https://github.com/remotely-save/remotely-save/assets/70559270/557b0fde-d3b7-4f13-ac97-1632fbc27310)

**Comment by tryzang** [comment]
I also had this problem after renaming a filename.

**Comment by fyears** [comment]
@Pongpun364 @tryzang i found the bug! please upgrade to 0.3.37. don't worry the bug doesn't cause data loss

@saurusss @huangjingyun8 your issue *might* come from the same bug or different one. please try to upgrade the version to see whether the issue is resolved or not. if not, feel free to reopen the issue.
