### ISSUE TITLE
[Feature Request]: Close Pop-up

### ISSUE THREAD

**Issue by cut01ass** [remotely-save/remotely-save#431]
### What feature are you suggesting?

![Screenshots_20240109205628](https://github.com/remotely-save/remotely-save/assets/96108931/e3a3bc16-596f-457b-bd3f-01e16735c2c4)
This sync message reminder pops up in the upper right corner every few seconds. Can you add a function to close this message? Or is there any way to turn it off? Thanks!

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
normally it would not show up unless you click the button. maybe something goes wrong on obsidian side. please try to close and reopen obsidian again.

**Comment by fyears** [comment]
or if you are using auto sync, please disable the plugin and restart obsidian and enable the plugin and try again

**Comment by youdaoxu** [comment]
I have similar interference prompts because I turned on synchronization when saving and set it to 10 seconds. When I edit a file, it automatically saves and starts synchronization. Maybe I edited the file or other operations triggered the save, and it will happen from time to time. There are similar tips.

This prompt is logically normal. It should be prompted when continuing to synchronize, but it bothers me. I hope to add a prompt to hide or enable options. The plug-in is very easy to use for me, thank you ~

**Comment by pettijohn** [comment]
"or if you are using auto sync, please disable the plugin and restart obsidian and enable the plugin and try again" - this worked to disable popups for auto sync every x minutes. Sync on Save popups still appear. Would be great to have an option for no popups, the sync status in the status bar is enough for me.

**Comment by vijayasantham12** [comment]
> "or if you are using auto sync, please disable the plugin and restart obsidian and enable the plugin and try again" - this worked to disable popups for auto sync every x minutes. Sync on Save popups still appear. Would be great to have an option for no popups, the sync status in the status bar is enough for me.

Yeah, there is an issue on sync on save functionality so,
I have raise PR #486 for this issue so you will not see popups once it gets merged

**Comment by fyears** [comment]
thanks @vijayasantham12 !
