### ISSUE TITLE
[Feature Request]: Obtrusive notifications «Save already running»

### ISSUE THREAD

**Issue by jerrygreen** [remotely-save/remotely-save#468]
### What feature are you suggesting?

So, there are 3 ways of auto-syncing:

- Startup sync
- Periodic sync
- Auto-save sync

Sometimes they are kind of «conflicting» with each other. For example, periodic sync started, then before it's completed – another one goes with auto-saving. Second one cannot start and shows me «save already running»

I was initially confused with it, and having not enough time to actually read the notification, I initially thought it's just a normal sync notification happening in background as I noted here:

- https://github.com/remotely-save/remotely-save/issues/401#issuecomment-1902484707
  > Those messages are a real distraction

Turns out, it's not just a normal notification, but it appears only when two separate syncs run simultaneously.

And honestly, I don't like to be notified about these «conflicts» that are not a problem at all, as it gets properly cancelled.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav (NextCloud)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Right now they are indeed (**should be**) exclusive running. E.g, if you are doing manual sync, the plugin will not start auto sync at this moment. after the syncing function is a "singleton".

anyways, i also think manual/auto/synconsave are too many, but i have no idea how to improve the different sync option, LOL. 

they come from different users' needs. any suggestions?

**Comment by jerrygreen** [comment]
I think this «singleton» idea is completely fine.

What I dislike is this «Save already running» notification – just remove it, or allow an option in settings, to hide it.

More precisely, I think if you have log level info – it should be hidden.
If log level is debug – we can show it, why not. Useful for debugging. Distraction otherwise.

**Comment by OzzmRT** [comment]
As far as I understand, this request is entirely related to mine, so I'll leave it here. Sync notifications superimposed overlap with subsequent error syncing progress notification are absolutely unnecessary and annoying.

![01](https://github.com/remotely-save/remotely-save/assets/154733768/4fc82ef0-9257-4897-aea8-4fca4ee3428a)

Although I'll note, these notifications occur strangely for me because they appear more frequently than every minute, as selected in my settings. It seems as if the notifications from Sync on Save overlap with each other when changes are made 🤷‍♂️

![02](https://github.com/remotely-save/remotely-save/assets/154733768/480b8a39-f074-4639-ae33-666bc6143fb4)

As for multiple sync options, I fundamentally disagree. The presence of manual and automatic sync is practically standard for sync services or sync-enabled applications, and the Sync on Save feature compensates for the need for faster automatic sync and allows all changes to be saved immediately, which is great. I tried using the remotely-sync plugin, which also supports all these sync options, and I didn't encounter such inconveniences because sync notifications superimposed overlap are simply absent. Therefore, in my opinion, for remotely-save as well, the best and most logical solution would be simply not to display the notification that sync is already running when automatic sync is taking place accordingly, the syncing progress notification is also unnecessary. Because such notifications are completely meaningless and unnecessary and this only clutters the notification, since automatic sync should be silent. But the notification that the sync has already started is of course necessary when we initiate sync manually to notify us that sync isn't being initiated because it's already in progress, and so that we also receive a notification upon its completion.

**Comment by MartinJDavis93** [comment]
They finally wrote about it. I didn't want to open such an issue on my own, because I'm probably perceived as some kind of asshole who's constantly dissatisfied with something in Remotely Save. But since I'm not the only one who is not satisfied with the plugin's work, I'll share a few words.

First off, let's address this question: What's the point of the Status Bar if all sync notifications are displayed as standard notifications anyway? I mean, seriously, what's the point? What's the sense in displaying "Synced less than a minute ago"? I don't get it. Its purpose was precisely to display the entire sync status, the stages of sync, for those who need that information, thus avoiding receiving any standard sync notifications and instead displaying all this information directly in it. But all we got is the message "Synced less than a minute ago." Thank you. Sincerely, thank you. Take a look at how it works in Remotely Sync to understand what the Status Bar was intended for in the general place.

Notifications during automatic sync. It's terrible. Just terrible. In principle, that's all. I don't know what else to add here. Yes, indeed, Sync On Save sync conflicts with itself, so Sync On Save notifications conflict with each other, overlap 🤦‍♂️ Therefore, every few seconds, practically after every new character or space, we get the notification "Remotely Save already running..." and as if just one notification wasn't enough for us, we get another notification with the progress of the sync 😩 (why do we need it???). On mobile devices, it's a disaster because notifications cover a significant portion of the screen, and you can't see the text in the first 2-3 lines because notifications cover it 🙈

To be honest, I'm completely tired of all of this, so I'll just summarize.

As @OzzmRT pointed out, automatic sync should be silent! And that's crucial. No unnecessary notifications, only critical ones, if any arise.

Regarding manual sync. Notification indicating the sync stage, in my opinion, is also unnecessary. Because previously, the main complaint was that Remotely Save generates too many unnecessary notifications during sync for the average user. Yes, it's normal during debugging, but not as a default option. If you really think that sync progress is useful for average users, then at least make this notification look normal because right now it looks like awful, like it's really some kind of error notification.

**Comment by valantur** [comment]
+1 to hiding the notifications on these types of conflicts. 
I wonder if it's possible to hide them via CSS, but I'm new to Obsidian and electron apps in general so IDK.

**Comment by fyears** [comment]
dup of #431
