### ISSUE TITLE
[Feature Request]: File name character limits

### ISSUE THREAD

**Issue by rootiest** [remotely-save/remotely-save#499]
### What feature are you suggesting?

I would like to request an option to set a character limit or allow it to be broken up into segments to address length limits on different hosting services.

Using Amazon S3 I have no issues, but when I try to sync with my own self-hosted [MinIO](https://min.io/) S3 server I receive errors in Obsidian during the sync. Despite this Remotely Save seems to still think it synced successfully, but it does not. The logs on my MinIO server show a large number of rejected PUTs with the following message: 
`error file name too long (*errors.errorString)`

From what I gather the file name character limit on AWS is just an open-ended 1024 characters, but on MinIO it is subject to additional restrictions. 

According to [their documentation](https://min.io/docs/minio/container/operations/checklists/thresholds.html):

> Maximum length for object names: 1024
> Maximum length for each / separated object name segment: 255

It seems that the file/object names being sent by Remotely Save are too long for my hosting service and they are being rejected as a result.

If setting a custom length limit is not possible, an alternative solution may be to break up the name into segments using `/` characters.

In its current state I am unable to use this plugin with my own S3 server and am forced to depend on Amazon or another paid service. 

If this request is too complicated to implement I will continue to use it that way, but I would love to be able to use my own hosted server for security/privacy/cost reasons! 

Thanks for your time, love this plugin, it's exactly what I have been looking for!

### What remote cloud services are you using, or suggesting adding the feature to?

S3, others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> an alternative solution may be to break up the name into segments using / characters.

actually this is already how the plugin works (if you are not using encryption). the full path from the root of the vault is set as the key. if you are using encryption, the key will be longer due to the base64 encoding. usually it shoud work well unless you have a deeply nested structure.

furthermore minio should return an error and the plugin should capture it...

would you like to provide further information: are you using password or not? can you give me an example of too long file name (with the path from the root of the vault)?

i would also suggest you not use a too deeply nested structure.

**Comment by rootiest** [comment]
Thanks for the quick response!

So based on your questions, I did some testing.

I **do** have some fairly long paths/note names as a result of mass importing them from a pretty large Google Keep collection.

I also **was** using a password/encryption.

And without encryption it syncs perfectly! The length of my note names don't seem to be an issue with encryption off.

Personally, I think I am ok with that as I will only be syncing over Wireguard to a server I control anyway.

I wasn't really able to repeat the "Remotely Sync thinks it synced successfully"

I was basing that on the fact that the status bar showed "Synced 1 minute ago" despite the sync having failed.

Now, even if I change the configuration, it still remembers the last successful sync and doesn't update when it fails. Maybe it was a fluke or maybe I did have a successful sync at one point without realizing it.

I did try again to enable encryption, this time with a much shorter password (my original password was 128 characters which it occurred to me might have an effect. However, even with a shorter password I was still unable to get a successful sync with encryption on.

This is an example of one of the errors in the MinIO log:

```
API: PutObject
Time: 15:57:50 UTC 02/15/2024
DeploymentID: e7d1a549-af53-494b-9cba-26bcbb9843a3
RequestID: 17B414797CF40EFA
RemoteHost: 100.78.53.123
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36
Error: drive:/minio-data, srcVolume: .minio.sys/tmp, srcPath: bc527f8e-8c4f-4dc6-ad92-5fc838c4c663, dstVolume: obsidian-encrypted:, dstPath: U2FsdGVkX19Qfy2s0AZu9w_wqUnpY42irPErngH9Zo_trfSQJL6vyO1OzWFtyUAU2zwi4h6IL-M_Og5FRHoej9fB8qWh3Yj8sPPEcsOWzhYQNb9uNnQeaojnIfWAwfXABY_8y08kNkR4Q2iTfdhL8LxFCuDwnMo2etAeNm1VFHMkzZWIST8YwCglNKwMCcWZ3tWJM0iAXD0O5UKr6D4Hlipoo1P2rcIDNo4F69b7tJezAVLtDlz0NiGj5Hn74AmB5WqaKRwjaZF1Gkc98RUv4B - error file name too long (*errors.errorString)

Backtrace: 
0: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
1: internal/logger/logonce.go:149:logger.LogOnceIf()
2: cmd/xl-storage.go:2385:cmd.(*xlStorage).RenameData.func1()
3: cmd/xl-storage.go:2441:cmd.(*xlStorage).RenameData()
4: cmd/xl-storage-disk-id-check.go:484:cmd.(*xlStorageDiskIDCheck).RenameData.func2()
5: internal/ioutil/ioutil.go:124:ioutil.WithDeadline[...].func1()
```

**Comment by fyears** [comment]
Password length doesn't influence the result length of encryption. The main problem comes from the fact that the encrypted file name is longer than the original file name and it exceeds the path length limit of minio.

The main difficulty comes from the fact that, the encryption name is almost "random string", so splitting them using `/` will generate lots of "independent folder containing only one file or sub folder". 

Switching to encryption by path is a solution (`aaa/bbb/ccc` -> `<enc of aaa>/<enc of bbb>/<enc of ccc>` instead of `<enc of aaa/bbb/ccc as a whole>`, which brings another drawback of leaking the path structure of the vault. I am planning on it but it needs some specific warning to users.

**Comment by fyears** [comment]
in the new version, a new rclone style encryption method is provided. it encrypts the file path by segments: a/b/c to <encrypt of a>/<enc of b>/<enc of c>, so the path length should be shorter.

feel free to make a backup manually and try the new encryption method. if it doesn't work either, then the only way is shortening yoir original file path, sorry.
