### ISSUE TITLE
[Feature Request]: Add the status bar on mobile

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#511]
### What feature are you suggesting?

https://forum.obsidian.md/t/css-to-show-status-bar-on-mobile-devices/77185/4

I find the way can show status bar on mobile. I try to show the sync status on status. But it display none.

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (腾讯云 COS Tencent Cloud COS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
@fyears I implemented this into Remotely Sync, so feel free to check out my last PR there. It still has some bugs though like the status bar covering the bottom row of buttons.

**Comment by HWiwoiiii** [comment]
> @fyears I implemented this into Remotely Sync, so feel free to check out my last PR there. It still has some bugs though like the status bar covering the bottom row of buttons.

What advantages does Remotely Sync offer compared to Remotely Save? Less Bugs I Hope? as I really need a secure approach to sync my vault from windows to ios.
Thank you~

**Comment by kadisonm** [comment]
@HWiwoiiii I'm not too knowledgeable about security but there is some information on it in the read me's. It would probably be best to ask the authors, but I'm sure if you set a long encryption password you'd be secure on either Remotely Sync or Remotely Save.

In terms of advantages Remotely Sync gets a lot more updates and new features but since Remotely Save has a larger user base it gets a lot more testing before releasing new features. Remotely Sync is quite the opposite where we make a new feature, release and fix the bugs in the next release.

**Comment by fyears** [comment]
>  I really need a secure approach to sync my vault from windows to ios.

really it depends on your threat model. 

if you are just a nobody and want to protect yourself from files being scanned automatically by big corps, i believe remotely save is good and reliable enough because it uses the same encryption as openssl.

if you are an important person i believe you need professional assistance which i have no comment

**Comment by fyears** [comment]
should be fixed on 0.4.4 (beta)

**Comment by kadisonm** [comment]
Not sure if I missed it so correct me if I'm wrong, but you should probably add a margin-bottom or similar to it to push it up above the toolbar on phones.

**Comment by fyears** [comment]
@kadisonm yes sure. I just need to debug on a mobile. https://github.com/remotely-save/remotely-save/commit/822941f1c3022819edf1b343859955270b89fa80 should be the fix and will come into next release. Thanks!
