### ISSUE TITLE
[Bug]: Removal of meta file causing sync slow by 10,000%.

### ISSUE THREAD

**Issue by ashrudral** [remotely-save/remotely-save#546]
### What feature are you suggesting?

Removal of meta file in the new update has caused sync to be slowed down by 10,000%. The sync that used to happen in 20 seconds for 3600 files, now happens in 40 minutes.

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
1. please ensure to update the plugin on every devices
2. don't worry, you situation might happen because the init sync of new version loses track of removals from old version. AFTER the init sync on EVERY devices, you can remove the files (either on yoir device or dropbox website), then sync, then the removals are synced again.

**Comment by fyears** [comment]
> 20 seconds for 3600 files, now happens in 40 minutes

It can only happen because of the unexpected files upload or download

**Comment by ashrudral** [comment]
> 2\. you can remove the files (either on yoir device or dropbox website), then sync, then the removals are synced again.

What files are you suggesting me to remove? All files or some particular files?

I don't understand what you refer to as "removals".

**Comment by fyears** [comment]
> The sync that used to happen in 20 seconds for 3600 files, now happens in 40 minutes.

## what might happen by not reading metadata files

firstly, let me explain the functionality of metadata file.

metadata files on the remote, only stores the information of "deletions from other devices". no more, no less.

for example, assuming you have files a,b,c on device 1, and have files a,b on dropbox, as well as "deletion record of c" in metadata file on dropbox.

in old version, the plugin in device 1 reads the metadata file firstly, then knows that c should be deleted, then delete the file c on device 1.

in new version, the plugin doesn't read the metadata file, and might be confused, and **might unexpectedly upload file c on device 1**. the new version has some logic to deal with the situation and migration but might have some edge cases not working.

as you can see, the only difference by not reading metadata file, is uploading c on device 1 unexpectedly. the workaround is manually deleting c on device 1, then of course no c would be uploaded.

if you see unexpected "deleted files" uploads and downloads, then the above is the reason of slowing down the syncs.

## but there might be other reasons

but, if you don't observe unexpected "already deleted files" uploads and downloads, then there might be some other reasons, which i have no clues yet. 

maybe only because of your network connections becoming slow, or maybe some files are being reuploaded because of the incorrectness of "last modified time" (they are not deleted but reuploaded), etc. 

i would suggest you make a backup of your vault firstly, and try to sync again to see whether the time come back to normal.

and please try to read the debug logs for some clues: https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/README.md

**Comment by ashrudral** [comment]
I deleted the plugin and it's files on both the cloud and local. Then reinstalled the new version. This time after the first sync it is working fine.
