### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by windtalkers9112** [remotely-save/remotely-save#58]
### What feature are you suggesting?

I have established synchronization on the wabdav service of my personal NAS, but I can't find the location of my synchronized data on the NAS. Does my NAS store data after synchronization? If so, where is the default data file stored?

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> Does my NAS store data after synchronization?

It should. And the files should be stored on your webdav location.

**Comment by windtalkers9112** [comment]
All my terminals can synchronize normally, but I can't find the synchronized stored data on my NAS. It's strange! My NAS is QNAP

**Comment by fyears** [comment]
Well, it seems the issue comes from QNAP side, not Remotely Save's side.

Suggestion: You could connect to QNAP webdav using Windows, like [this](https://www.qnap.com/en-us/how-to/knowledge-base/article/connecting-to-webdav-shared-folders-on-a-qnap-nas-in-windows-10), or any other general-purposes' webdav client, like [cyberduck](https://cyberduck.io/webdav/). Then test around it, and try to figure out the locations of webdav files saved on your QNAP.

Since there is not so much I can do, I am closing this issue at this moment. If you are sure that there's a bug in Remotely Save, instead of a configuration issue of QNAP, feel free to reopen the issue.
