### ISSUE TITLE
[Bug]: obsidian mobile is crashing when i want to sync my remaining files to the phone.

### ISSUE THREAD

**Issue by eiliatmr** [remotely-save/remotely-save#595]
### What happened?

I noticed that obsidian would crash after syncing some files when i use remotely save sync btn.

First it happend after every 30(maybe less maybe more) file sync from the cloud to the phone.

And after 751 files, it crashes when i try to click sync.
It doesnt get any more files.

Ik this isnt really helpful for finding the bug or reason for such behavior but i will put it here for now till we see if its obsidian related or plugin related

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
any big files are you using?

**Comment by TixieSalander** [comment]
Same issue here, both on my iPhone and iPad. 
Yes I have a big vault (since It's for now not possible to get some plugins share between all my vault I've one vault with all my projects in it. Not ideal but didn't found a better solution yet)

I first tested on my phone who isn't a beast so it though it was the plugin asking for too much resources.
But I also tested on my iPad Pro from 2022 and same issues.
Thought it was caused by the big number of files to initially sync. So I've tweaked the settings to limit the concurrent transferts to 2, and limit sync to files under 50Mo). But it's  still crashing even if the all files are now synced and I'm barely editing a markdown note 😔.

Is there a way I could get maybe crash reports I could then send you to help?

**Comment by fyears** [comment]
@TixieSalander hi thanks for your report and sorry to hear the crash. i would try to implement some "crash report" in next versions.

"how many files in total in the vault" should not be the issue. but "some files having large size" (e.g, a file with 50 mb or more) might be the issue. would uou like to check if your vault contains such files? if that's the root cause, you could set "skip large files" in the settings
