### ISSUE TITLE
[Bug]: Cannot sync on iPhone and iPad. Obsidian crashes.

### ISSUE THREAD

**Issue by WowLucy** [remotely-save/remotely-save#603]
### What happened?

I have turned on the debug level. The plugin is successful up to step 6. It is running and did not show step 7. After a really long time (like an hour), the entire app crashes. The plugin was okay before the update. After the update and I changed to using RClone to start a new sync, the sync never worked. I have 10,000+ files. The sync works on Mac, but when sync on iPhone and iPad, it does not work on both.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by WowLucy** [comment]
I tried multiple times on iPhone and Obsidian auto restarts. Remotely-save saying at stage generating plans. Cannot work. Please help. Thank you.

**Comment by fyears** [comment]
how many files in your vault? 

would you like to reduce the concurrency setting?

**Comment by WowLucy** [comment]
I have 10000+ files (plus files in .obsidian would be 17000+). 
I set the concurrency to 1, but it still does not work. It is running in stage generating_plan for about an hour, and then Obsidian auto restarts.

**Comment by fyears** [comment]
I have added two debug settings.

1. install latest remotely save (v0.4.21)
2. go to remotely save setting, scroll down to very end, you will see two new settings: "Enable Profiler Printing" and "Enable Profiler Recording Size", enable them both.
![xxx](https://github.com/remotely-save/remotely-save/assets/1142836/915c26f9-1bd4-435d-9b67-41fecd8b246d)

4. please install another plugin for recording logs easily on mobile: [`logstravaganza`](https://github.com/czottmann/obsidian-logstravaganza)
5. enable logstravaganza,change the output format to "markdown code blocks".
6. trigger the sync of remotely save. in the meanwhile, logstravaganza should generate a file called `console-log.<device>.md` into the root of the vault. Even if your device crashs, the log file might have saved some hints.
7. disable logstravaganza after the first failed sync. so that the log file is not written later.
8. checkout the log file, and find out any useful info in the end of the log file. for example, you can see precisely where the app crashes, and you can see the size of some large objects (keyword: `sizeof`). remove any sensitive info and paste them into a github gist and paste a link here. 
![yyy](https://github.com/remotely-save/remotely-save/assets/1142836/ef9e6fcd-b66c-4b09-91af-c5a5cc966b1f)

**Comment by fyears** [comment]
close due to no response. but anyways reducing large files should work
