### ISSUE TITLE
[Bug]: Can't accept sync algorithm change dialog on mobile

### ISSUE THREAD

**Issue by wkbaran** [remotely-save/remotely-save#619]
### What happened?

When the dialog, "Remotely Save has HUGE updates on the sync algorithm" opens, clicking 'Agree' does nothing. Clicking 'Do Not Agree' or the 'X' leaves the plugin enabled, but not configured. No sync options are available, etc.
![obsidian_remotelysave_mobilealert](https://github.com/remotely-save/remotely-save/assets/2525633/d378c21d-d2c9-4df6-afe7-36def042c58e)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
there should be checkboxes in the beginn of the line "i will backup..." and "i understand i need to ...", 

maybe your obsidian theme has some werid effect then the checkbox doesn't show up. i don't know how to fix this because normally they will show up and no other users complain so far...

would you like to change your theme and try again, or just try to read and **click** the checkbox **lines** then click the confirm button?

**Comment by bill-accessidaho** [comment]
Yes, the problem was with the Minimal theme. Thank you!
