### ISSUE TITLE
[Feature Request]: "Abort Sync If Modification Above Percentage" allow override

### ISSUE THREAD

**Issue by sfwr** [remotely-save/remotely-save#685]
### What feature are you suggesting?

Allow an in-line override of the setting

> Abort Sync If Modification Above Percentage

Right now, if I make a lot of changes and need to sync to my devices, the workflow is

**Device 1**
- Make a lot of changes 

**Device 2, 3, N**
- Go into settings, change setting to 100%
- Exit settings
- Sync
- Go into settings, change setting back to 50%

After doing this a few times, I'm inclined to just leave the setting at 100, which is likely not the intended user-experience for this setting.

It'd be nice to have a warning instead that we are about to sync 50%+, and allow the user to confirm or reject the change in a popup modal or something similar, rather than requiring the existing cumbersome workflow.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav (NextCloud)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
why would you *always* have lots of changes?

**Comment by fyears** [comment]
i mean, usually only a few notes are chaneged and that's the assumption behind the protection ( to avoid anything unexpected)

**Comment by fyears** [comment]
Close due to the complexity of UX.

**Comment by AbdelrahmanHafez** [comment]
Hi @fyears, I learned today about Remotely Save, and I love it so far!
However, I came across this issue especially on the first save, I think this adds unnecessary friction, and instead of making it error out, the UX would be simpler to have a "Cancel Sync"/"Sync Anyway" buttons just under it, while having the knob in the settings.

I'd argue that users are more likely to leave it at 100% due to the friction (or because they forgot) with the current setup.
I'm happy to work on this if you're open to it when/if you plan to continue working on the plugin in the future.
