### ISSUE TITLE
[Bug]: Cannot work together with additional synchronization.

### ISSUE THREAD

**Issue by jsrdcht** [remotely-save/remotely-save#711]
### What happened?

Assuming there are computer A (MAC OS) and computer B (Windows), copying the entire library manually from computer A to computer B, then running remotely save on computer B will prompt that 95% of files will be deleted.

### What OS are you using?

Windows, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.5.5

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
It says 95% will be **modified** or deleted, not deleted only.

Because in your way, the last modified time of the files on macos and windows are different.

Please back up your vault elsewhere, then allow the sync by disabling the protection, then sync **once** on B, then sync **once** on A, thrn enable the protection on both devices. Your files and sync info should be ok now.
