### ISSUE TITLE
[Bug]: remotely-save decided that my vault need to be whiped?

### ISSUE THREAD

**Issue by INPoppoRTUNE** [remotely-save/remotely-save#739]
### What happened?

My vault is not empty:
![image](https://github.com/remotely-save/remotely-save/assets/23138929/73fec659-8e5c-450e-9379-ba05954d96d9)
but remotely-save seems to think that it need to edit (aka _delete_) all 1520 of my files (ask me how I know).

I'm not able to sync any files as the protection is triggered. How may I clear the "empty vault" as the previous sync data that it is trying to replicate on my local vault?

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.12

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you have any data in dropbox website?

do you have any data on other machine and using remotely save there?

any steps to reproduce this error?


And I **STRONGLY** recommend you make a backup of your vault firstly to avoid any unexpected data lost.

**Comment by INPoppoRTUNE** [comment]
> do you have any data on other machine and using remotely save there?
Yes, this is the 4th machine I'm connecting to remotely-save.
Everything worked smoothly until I configured this last one: I downloaded all files from Dropbox directly inside the local vault folder, then launch a sync.

> do you have any data in dropbox website?
Yes, even tho I had to retrieve some files from the trashcan as it tried to delete them all.
I can see all files inside dropbox, but now each of the 4 devices are trying to delete all files.

> any steps to reproduce this error?
See configuration step.

> And I **STRONGLY** recommend you make a backup of your vault firstly to avoid any unexpected data lost.
I have 4 local copies of the vault and remotely-save temporarily disabled, thanks anyway for the heads up.

**Comment by fyears** [comment]
> I downloaded all files from Dropbox directly inside the local vault folder, then launch a sync.

that’s the point. 

explain: 

the plugin relies on the last modified time , and builds a mapping between local last modified time and remote last modified time (they are unfortunately usually different). but you manually copied the files into the vault, exactly making the plugin confused because the plugin doesn’t have the mapping and thinks your local and remote are different!

solution:

if you are sure the copy on dropbox website is the perfect one, then just delete **everything in vault locally**, (remember to disable syncing .obsidian as well) (and delete everything, not partially). then the plugin will think your local vault is empty and will download everything from dropbox website **and build the mapping (index) correctly**

i am sorry for the inconvenience, but it’s a difficult technical problem and no easy way to workaround.

**Comment by fyears** [comment]
> I can see all files inside dropbox, but now each of the 4 devices are trying to delete all files.

if you manually edit all files on dropbox the all devices’ mappings are corrupted. make a backup of the dropbox one elsewhere firstly and empty local devices and repeat the steps I said above. the plugin should download the files from dropbox website and build the mapping/index again.

**Comment by INPoppoRTUNE** [comment]
> > I can see all files inside dropbox, but now each of the 4 devices are trying to delete all files.
> 
> if you manually edit all files on dropbox the all devices’ mappings are corrupted. make a backup of the dropbox one elsewhere firstly and empty local devices and repeat the steps I said above. the plugin should download the files from dropbox website and build the mapping/index again.

I renamed the vault folder, re-created the original vault from scratch, enabled remotely-save and it's working again.
Thanks for your time!
