### ISSUE TITLE
[Bug]: Sync breaks on unusal file names, debugging is hard

### ISSUE THREAD

**Issue by RobTranquillo** [remotely-save/remotely-save#798]
### What happened?

I am using the plugin on Android 14, Samsung OneUI 6.1 and using Nextcloud 29.0.1 via WebDav

I'm about to switch from my MediaWiki system for notes to Obsidian and still very new to Obsidian. I've written a little scraper that writes each wiki page to a markdown file.  This creates files with unusual but not forbidden characters like : and /, which aborts the synchronisation process without any helpful message or debugging. I only found this problem by manually synchronising over 400 files.

I had also switched on logging and checked the log files, or tried to. Because the log file, although only 500kb small, causes Obsidian TextEditor (and another one I tried) to freeze. Mainly I think because the file-sync-json object contains all +400 files in one super wide line.

Other than that, the plugin works great. Thanks a lot for that! I love being able to sync via Android much faster than with file folder/file sync apps. 

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7 (149)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Coincidently a few hour before I release a new version showing errors if your sync is interrupted by invalid characters in folder / file names, maybe you can try.

Also, since you know how to code ("I've written a little scraper"), may be you can directly checkout:

1. https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
2. `/` `\` are also not allowed because they are part of the file paths
3. https://github.com/remotely-save/remotely-save/blob/fcdbb7149328fe304de420937c659f7c8bae5d4d/src/misc.ts#L750-L851
