### ISSUE TITLE
Password Reset for Pro Version

### ISSUE THREAD

**Issue by hotstunna80** [remotely-save/remotely-save#824]
### What feature are you suggesting?

Need a way to reset our password for the remotelysave.com site, so we can login if we forget our password for the Pro version of the plugin. Also, you should make sure you can check your emails with this plugin’s website. You probably have emails from other people besides me. I was considering patronizing you and can’t now. 

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Yeah you are absolutely correct. The only way to reset the password is directly use your account email to send an email to me to request so that I can delete the account and you register the account again. (I cannot see your password too because it's salted and encrypted.) Because actually during the beta everything is free (except users having to manually enable the features) so it's not harmful to do that.

Fixing the plugin and stabilizing the feature are higher priority on my list. Resetting the password on the website will be added in the end of the beta.

Thank you for you reporting
