### ISSUE TITLE
[Feature Request]: Ability to sync immediately at startup.

### ISSUE THREAD

**Issue by ivanmood0** [remotely-save/remotely-save#89]
### What feature are you suggesting?

The syncing 10 seconds after launch is quite long, leaving you in a half position (and there is no point in sync manually, because you need to wait a few more seconds for automatic sync, and at the same time, you also do not really want to wait). This is quite inconvenient if you need to quickly view a note that is not yet sync. Therefore, it would be great to add the ability to synchronize immediately at startup (or add, for example, an interval of 1 second). Thx.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the initial point of providing the 10 sec option, was that maybe some other plugins may do something after starting up obsidian and i wanted to wait until the status got stable.

that being said, i will add the 1 sec option as you suggested, so that users can have more choices. the new option will come with next release.
