### ISSUE TITLE
[Bug]: Large file transfers and validations hang/crash obsidian.

### ISSUE THREAD

**Issue by ColColonCleaner** [remotely-save/remotely-save#97]
### What happened?

Thank you very much for making this. I was very happy to find it since it avoids the 10GB size limit on Obsidian's official vault sync.

I took some videos with my phone so I could transcribe to notes later when back on my PC. These videos range from 700MB to 1.5GB, 6 of them, MP4 format which Obsidian supports. Added them to my attachments directory in the vault and requested a sync. Note that I'm using manual sync, not automatic/scheduled. My provider is Dropbox, phone is android, PC is windows 10.

Problems on mobile: Requesting a sync to upload these files hangs the app, which automatically kills itself not long after.

Problems on PC: I uploaded the files manually through dropbox since sync was hanging in obsidian and tried downloading them on PC via sync. It was able to download them all after a few tries/crashes. Now there is another problem. It appears the validator that compares the files is trying to download them again because when I call for a sync (with no local changes to the vault) it starts a large download (i see the network transfer rate spike), loads 6GB of data into memory, and then the app goes blank and never recovers. I believe there needs to be a simple file metadata comparison for files larger than a certain size to avoid this happening, but there might be a better way to handle it.

### What OS are you using?

Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.19

### Version of Obsidian

Android: 1.2.0 (50), API v0.14.2
PC: v0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ColColonCleaner** [comment]
Edited to add specific versions of obsidian for both Android and PC.

**Comment by fyears** [comment]
Thanks for your report, and I am so sorry that you meet the issue while using the plugin.

> I believe there needs to be a simple file metadata comparison for files larger than a certain size to avoid this happening, but there might be a better way to handle it.

I totally agree with you. Due to the technical limitations, there is no better way to avoid loading the total files into memory (Obsidian doesn't support uploading the files in **streaming** easily). And furthermore, maybe it's not a good idea to "bidirectional sync" any large files.

One practical solution on the plugin's side, is adding the feature to avoid the files larger than a specified size. Or even better, adding another feature to "ignore" some files in the settings.

Currently.
1. **Always remember to backup your large files elsewhere beforehand to avoid any bad things.** 
2. You need to wait for [this feature](https://github.com/remotely-save/remotely-save/issues/50) to be implemented. 
3. **Or**, because the plugin deliberately ignore the files starting with `_` (underscore) by default, you can rename the file name from `xxx` to `_xxx` to make the plugin not sync those files. (Make a backup beforehand!!)
